import type { DashboardData } from "./types";

export const demoData: DashboardData = {
  isDemo: true,
  metrics: {
    spend: 86.4,
    conversations: 24,
    qualified: 17,
    quotes: 11,
    sales: 5,
    revenue: 2480,
    costPerConversation: 3.6,
    costPerSale: 17.28,
    leadToSaleRate: 20.8,
  },
  cities: [
    { city: "Ribeirão Preto", leads: 13, qualified: 11, quotes: 8, sales: 4, revenue: 2070, conversionRate: 30.8 },
    { city: "Sertãozinho", leads: 4, qualified: 3, quotes: 2, sales: 1, revenue: 410, conversionRate: 25 },
    { city: "Cravinhos", leads: 3, qualified: 2, quotes: 1, sales: 0, revenue: 0, conversionRate: 0 },
    { city: "Serrana", leads: 2, qualified: 1, quotes: 0, sales: 0, revenue: 0, conversionRate: 0 },
    { city: "Não identificada", leads: 2, qualified: 0, quotes: 0, sales: 0, revenue: 0, conversionRate: 0 },
  ],
  leads: [
    {
      id: "demo-1",
      name: "Mariana",
      phone: "(16) 9••••-1042",
      city: "Ribeirão Preto",
      neighborhood: "Jardim Paulista",
      service: "Sacada",
      status: "fechado",
      source: "Instagram Ads",
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Gato no quintal",
      quoteValue: 520,
      saleValue: 520,
      cityConfidence: 1,
      citySource: "texto_direto",
      createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    },
    {
      id: "demo-2",
      name: "Carlos",
      phone: "(16) 9••••-8861",
      city: "Sertãozinho",
      neighborhood: "Centro",
      service: "Janela",
      status: "orcamento",
      source: "Instagram Ads",
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Sacada segura",
      quoteValue: 390,
      saleValue: null,
      cityConfidence: 1,
      citySource: "texto_direto",
      createdAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    },
    {
      id: "demo-3",
      name: "Ana",
      phone: "(16) 9••••-4510",
      city: "Ribeirão Preto",
      neighborhood: "Ipiranga",
      service: "Quintal",
      status: "qualificado",
      source: "Instagram Ads",
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Gato no quintal",
      quoteValue: null,
      saleValue: null,
      cityConfidence: 1,
      citySource: "bairro",
      createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    },
    {
      id: "demo-4",
      name: null,
      phone: "(16) 9••••-2298",
      city: "Cravinhos",
      neighborhood: null,
      service: "Sacada",
      status: "novo",
      source: "Instagram Ads",
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Gato no quintal",
      quoteValue: null,
      saleValue: null,
      cityConfidence: 0.93,
      citySource: "fuzzy",
      createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
  ],
  ads: [
    {
      date: new Date().toISOString().slice(0, 10),
      spend: 42.8,
      impressions: 2880,
      reach: 2420,
      conversations: 13,
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Gato no quintal",
    },
    {
      date: new Date().toISOString().slice(0, 10),
      spend: 43.6,
      impressions: 2510,
      reach: 2140,
      conversations: 11,
      campaignName: "SOS | WhatsApp",
      adsetName: "Ribeirão e região",
      adName: "Sacada segura",
    },
  ],
  integrations: {
    database: false,
    whatsapp: false,
    metaAds: false,
  },
};
